### ISSUE TITLE
Update annotation property for 'intestinal stem cell' from 'has_exact_synonym' to 'has_obo_namespace'

### ISSUE THREAD

**Issue by chris-grove** [xenopus-anatomy/xao#58]
The term 'intestinal stem cell' (XAO:0005236) currently has a 'has_exact_synonym' annotation to 'xenopus anatomy' and is missing any 'has_obo_namespace' annotation, unlike all other terms in the ontology:

<img width="626" alt="Screen Shot 2022-04-22 at 10 31 09 AM" src="https://user-images.githubusercontent.com/611382/164735412-9526738c-3a79-4f78-9442-396b97271de6.png">

I suspect that was intended to be a 'has_obo_namespace' annotation to properly declare the namespace of the term.

**Comment by seger** [comment]
Fixed in new release.
