### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by cthoyt** [xenopus-anatomy/xao#59]
I want to add an annotation to this ontology for what the root terms are. Should I edit the OWL or the OBO file?

**Comment by cthoyt** [comment]
Hi @seger, I wouldn't mark this issue as complete without a response or update to the repository. Since XAO is part of the OBO Foundry, there's sort of an expectation that these kinds of questions get answered. Just a comment would be nice, thanks

**Comment by seger** [comment]
@cthoyt Sorry about that, I was catching up after vacation and racing through tasks a bit too quickly. But yes, for this it suffices to edit the OBO file.
